apiVersion: v1
kind: Pod
metadata:
  name: hello
  namespace: dev
spec:
  containers:
  - name: redis
    image: redis
  - name: memcached
    image: memcached
    image: memcached
---
apiVersion: v1
kind: Pod
metadata:
  name: hello
  namespace: qa
spec:
  containers:
  - name: redis
    image: redis
  - name: memcached
    image: memcached

