apiVersion: v1
kind: Pod
metadata:
  name: kucc1
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
  - name: redis
    image: redis
    ports:
    - containerPort: 6379
  - name: memcached
    image: memcached
    ports:
    - containerPort: 11211
  - name: hashi
    image: hashicorp/consul
    ports:
    - containerPort: 8500    

